stages:
  - test
  - deploy

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.46.1-jammy
  script:
    - mkdir -p playwright-report
    - echo "Install Dependencies"
    - npm ci
    - echo "Install browsers"
    - npx playwright install
    - echo "Run Tests"
    - npx playwright test --reporter=html
  artifacts:
    paths:
      - playwright-report/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r playwright-report/* public/
  artifacts:
    paths:
      - public
  only:
    - main