stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.46.1-jammy
  script:
    - mkdir -p playwright-report/screenshots
    - echo "Install Dependencies"
    - npm ci
    - echo "Install browsers"
    - npx playwright install
    - echo "Run Tests"
    - npx playwright test --reporter=line,html
  artifacts:
    paths:
      - playwright-report/
    expire_in: 1 week
